<!-- For Errors Generated By Submitting form without required fields: -->

@if(count($errors)>0)
    <div class="alert alert-danger">

        @foreach($errors->all() as $error)

            {{$error}}
            <br>

            @endforeach

    </div>

    @endif

<!-- For Success Message Flash: -->
@if(session('success'))

    <div class="alert alert-success">

        {{session('success')}}

    </div>

    @endif


<!-- For User Errors: -->
@if(session('error'))

    <div class="alert alert-danger">
        {{session('error')}}

    </div>

    @endif